application: change-me
version: logcollector
runtime: python
api_version: 1
threadsafe: no

handlers:

- url: /logcollector/
  script: main.py
  login: admin

- url: /fantasm/.*
  script: fantasm/main.py
  login: admin

  